# Generated by Django 4.1.7 on 2023-05-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attendancelogs_id_alter_board_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='a_logged_in_time',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='attendancelogs',
            name='a_logged_out_time',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
