# Generated by Django 4.1.7 on 2023-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_attendancelogs_a_logged_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='logged_in_total',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
